### PR TITLE
Fix too sensitive entering visual mode on mouse click.

### PR DESCRIPTION
**Pull request by cho45**
Sometimes, unexpected visual mode entering by just clicking editor window.

### CODE REVIEW

**Comment by montague** [comment]
:+1: for this--happens to me regularly. i use an apple track pad.

**Comment by jschaf** [comment]
I've run into this a couple times.  I would like to stay in normal mode if I mouse-drag in just a single letter.

**Comment by scott-hand** [comment]
I would love for this to be merged. For some reason, this isn't an issue on Linux, but it makes IdeaVim next to useless for me on Windows.

**Comment by vlasovskikh** [comment]
@scott-hand Does it affect MacOS X? I'll check in on Windows.

**Comment by montague** [comment]
@vlasovskikh i use OS X and it affects me.

**Comment by hopperath** [comment]
This happens to me all the time and is very frustrating. I agree that mouse drag within a char is too sensitive activate selection.

**Comment by vlasovskikh** [comment]
I still cannot reproduce the problem and I cannot verify that the suggested PR really fixes it. From what I see it doesn't change the behavior of single-character selection when you move your mouse over less than one character.

Could anyone please record a screencast showing the problem?

**Comment by ayzenquwe** [comment]
@vlasovskikh, if I understand the problem correctly, it's quite easy to reproduce it (on mac): just click anywhere and slightly move a mouse cursor within a clicked character (without releasing a mouse button). The result: visual mode is activated. Original vim with mouse support doesn't activate visual mode if you move a cursor within a single character. Does it make sense?

**Comment by scott-hand** [comment]
Here's an image showing the problem:

Pycharm Sadness

**Comment by vlasovskikh** [comment]
@ayzenquwe @scott-hand Thank you! Now I get it. The related issue is [VIM-1098|https://youtrack.jetbrains.com/issue/VIM-1098].

**Comment by vlasovskikh** [comment]
The proposed change doesn't fix the problem. I can reproduce it in both cases. I will see what's going on here.

**Comment by vlasovskikh** [comment]
An alternative fix is available in the build 0.46.1 via the Early Access Program, see https://github.com/JetBrains/ideavim#get-an-early-access for details. Give it a try!

Please post any comments to [VIM-1098](https://youtrack.jetbrains.com/issue/VIM-1098).

**Comment by hopperath** [comment]
This fixed it for me. Thanks for the fast turnaround!

**Pull request closed without merging**
