### PR TITLE
Get indent from PsiFile so formatting on shift is consistent (VIM-1231)

### PR DESCRIPTION
**Pull request by apottere**
Fixes https://youtrack.jetbrains.net/issue/VIM-1231

I wasn't sure what the difference was between `PlatformDataKeys.PROJECT.getData(context)` and `editor.getProject()`, so I opted to leave the current behavior (former) where `context` was available.

### CODE REVIEW

**Comment by apottere** [comment]
Also, not sure if you mind the editorconfig coming in but I felt it was ok since the current format doesn't match editor defaults.  I can remove it if you'd like to add it yourself.

**Comment by apottere** [comment]
@vlasovskikh any chance you could review this?  I've been using these changes for a while now and they seem to work.

**Comment by AlexPl292** [comment]
HI @apottere !
Thank you for such a long wait and for your PR!

**Comment by apottere** [comment]
@AlexPl292 Thanks for merging it!

**Pull request merged**
