### PR TITLE
VIM-892 Fix focus issues when executing :action commands from a keymap

### PR DESCRIPTION
**Pull request by smartbomb**
also fixes VIM-1001, VIM-1016 and hopefully VIM-962 but unable to fully reproduce

### CODE REVIEW

**Comment by vlasovskikh** [comment]
Thanks for your PR! I've added one more level of `invokeLater` (+1 to the amount of levels of `requestFocus()` in order to guarantee the sequential execution.

**Comment by avendael** [comment]
Is this already in the plugin's latest version? I still experience the focus issues :disappointed:

**Comment by vlasovskikh** [comment]
@avendael Get the latest CI build from [here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=IdeaVim_Build&guest=1).

**Comment by avendael** [comment]
Thanks!

**Comment by naseer** [comment]
Is this available in 0.44 ?

**Pull request merged**
