### PR TITLE
[VIM-1012] Support tab close preferences when using :q or :wq

### PR DESCRIPTION
**Pull request by bradziolko**
Hello friends!

This PR fixes [VIM-1012](https://youtrack.jetbrains.com/issue/VIM-1012)

The issue is that when you use `:q` or `:wq` or any other variants, ideavim will always focus the tab to the right unless it is the final tab in the group.  It should be honoring the intellij preference that allows you to configure focusing the left, right, or most recently used editor.

The `closeFile` method has protections in place in order to not close all of the tabs of the same file.  However, this implementation naively increments the focused tab index and moves on.  The intellij file editor api has an implementation that basically duplicates most of ideavim's `closeFile()` method while also honoring the directional preferences.  You can see that method [here](https://github.com/JetBrains/intellij-community/blob/5c50417af6df5c7e259067ba7ffe96d814e6a0c3/platform/platform-impl/src/com/intellij/openapi/fileEditor/impl/EditorWindow.java#L212-L293).  I've changed the method to use the file editor api and tested that it works. 

The method that I used to test was to:

* Open multiple tabs
* Set preferences in Editor -> General -> Editor Tabs to activate the tab on the left
* Close a middle tab with `:q`
* Note that it focuses the tab to the left correctly

The same can be done for the mru tab.

You can test that it does not close all instances of the same file using these steps:

* Open a file in the editor
* Go to Window -> Editor Tabs -> Split Veritcally/Horizontally
* This should open the same file in two tabs/split editors
* Use the command `:q` to close the editor and see that one of the tabs remains open

The incorrect functionality can be enabled by replacing `window.closeFile()` on line 158 with `fileEditorManager.closeFile()`.  You can then test using those same steps and see that it will close both editors when using the `:q` command.  The `FileEditorManagerEx` class explicitly closes all instances of the same VirtualFile.

Sorry for the lengthy PR description, but this is my first contribution to the project and I'm trying to be thorough.

Thanks!

### CODE REVIEW

**Comment by citizenmatt** [comment]
This also fixes a bug bear of mine that `:q` doesn't remove the closed file from the CTRL-TAB Switcher. +1 from me!

**Comment by bradziolko** [comment]
@vlasovskikh Is there anything I could assist with to help this get reviewed and merged?  Or any concerns I could address?

**Comment by AlexPl292** [comment]
Hi @bradziolko!
Me and @vlasovskikh started to review all existing PRs in bottom up order. I apologize for the long wait, I'll review your PR today.

**Comment by AlexPl292** [comment]
This is a great description of PR. It answered all my questions during the investigation. Thank your for PR!

**Comment by bradziolko** [comment]
@AlexPl292 Awesome, thanks for the snappy response!  Understandable about the bottom up ordering.  Do you know which version this will be cut after and when that'll release?  I've not had any insight into your versioning process yet.

**Comment by AlexPl292** [comment]
The public release was a few weeks ago, so the the next one will be in 2-3 months. You can join [EAP](https://github.com/JetBrains/ideavim#get-an-early-access) program to get all the new features faster. EAP release will be in a week or two.

**Comment by bradziolko** [comment]
👍 awesome, I'll probably do that so I can start using this ASAP!

**Pull request merged**
