### PR TITLE
Add rudimentary command support

### PR DESCRIPTION
**Pull request by hari-rangarajan**
Experimenting with a simple ":command" interface. Allows mapping intellij custom actions to shorter commands as desired. For example  ":command shell action openTerminal"  to open shell instead of requiring a custom action in java code.

No unit test (as of yet). Would appreciate initial comments.

### CODE REVIEW

**Comment by hari-rangarajan** [comment]
@johngrib Might be of interest as you have been adding custom command wrappers for :shell and :vim.

**Comment by vlasovskikh** [comment]
@hari-rangarajan What's wrong with existing `:action`? E.g. `:action ActivateTerminalToolWindow`?

**Comment by hari-rangarajan** [comment]
Too verbose and I can't remember any of the action commands. Without auto completion, it is practically not usable IMHO.  It would be easier to map it to simpler commands that work personally (in the spirit of the original vim :command). Also, I prefer typing a command than using a shortcut.

I see similar fine-grained attempts at this in the pull request:
https://github.com/JetBrains/ideavim/pull/116
https://github.com/JetBrains/ideavim/pull/115

**Comment by vlasovskikh** [comment]
See the docs in README about using `:actionlist`. You can map `:action ...` to any shortcuts you like using `:map` commands.

**Comment by gaganis** [comment]
Typing long actions is not ideal and I hadn't considered using :map until now. Looks like a really cool feature that I will definitely look into. Thanks @vlasovskikh 

@hari-rangarajan Can you provide a small clarification, please? In your PR would :command be only able to map to actions?

In the original vim :command is used as a much more general mechanism where you can assign any replacement text as a user command. If we were to introduce :command I would have liked that we tried to make more generic and not cover only a special case.

**Comment by hari-rangarajan** [comment]
@gaganis It is wrapping any Ex command into a command name. So you can execute any other Ex command with it too.

@vlasovskikh It is just me. I prefer to use Ex commands instead of mapping for commands I use rarely. It is hard for me to remember many cryptic mappings and I have to type it fast  if you are treating that as a shortcut.

**Comment by gaganis** [comment]
I also am a fan of Ex commands to be honest so I look favorably at this.

I will try to pull this into my local build to check it out over the next days.

**Comment by icholy** [comment]
I found this issue while trying to figure out how to map `:bd` to `:action CloseActiveTab`

**Comment by hari-rangarajan** [comment]
For anyone interested, I'm experimenting with an auto-completeable Vim command line interface: https://github.com/hari-rangarajan/IdeaExActionBar

I used stock IntelliJ components to get the auto-complete working plus ideaVim's command line panel code. It would require some work to integrate it back to ideaVim because it uses Swing components directly but it can live as an individual plugin and complement ideaVim.

**Comment by icholy** [comment]
@hari-rangarajan that looks great!!

**Comment by mikeholler** [comment]
Any chance of this getting in anytime soon? I'm really interested in this feature.

**Comment by AlexPl292** [comment]
Hi @hari-rangarajan !
What about the status of this PR? As I see, it's not yet complete and allows only mapping to `action` commands, right?
We'd like to have more powerful `command` support. More similar to real vim. Do you have plans to continue this PR?

**Comment by AlexPl292** [comment]
Closed due to no response and new PR: https://github.com/JetBrains/ideavim/pull/181

**Pull request closed without merging**
