### PR TITLE
Implement iskeyword

### PR DESCRIPTION
**Pull request by nickgieschen**
This commit implements vim's iskeyword feature. I do a lot of clojure in IDEA these days and want to be able to specify that a hyphen is part of a word. Of course, you can add and remove any other characters to and from the keyword list, if you'd like. I've included a bunch of unit tests to cover all the edge cases I could think of. 

Also, the following three tests weren't passing before I made my changes (just so you know my changes didn't break those tests):

testAutoCompleteCurlyBraceWithEnterWithinFunctionBody
testDeleteBothParensAndStartAgain
testRepeatWithParensAndQuotesAutoInsertion

### CODE REVIEW

**Comment by vlasovskikh** [comment]
@nickgieschen Thanks for your new updates to this PR, I'll review them a bit later.

**Comment by nickgieschen** [comment]
Hi. Just wondering if there's anything else I can do to get this pulled in. Thanks!

**Comment by snoe** [comment]
It's almost been a year but with the release of the https://github.com/cursive-ide plugin for clojure, more and more people have been waiting for this functionality.

**Comment by pangloss** [comment]
I'm also using Cursive and would really like to be able to add the "-" character as a keyword. As it is I'm unable to use * or #, which are integral to my workflow. I'm afraid I cannot buy Cursive until this goes in, which is a shame because I know the author of Cursive is not the one responsible.

**Comment by shinichy** [comment]
Any update? I think this feature is crucial for Cursive users.

**Comment by libgcc** [comment]
@vlasovskikh I'm waiting for this feature, it's certainly useful. Have you decided merge or not, it's a long time

**Comment by pkrefta** [comment]
Hey guys - is there any for this to get finished and merged ? 

I'd love to see this option in Ideavim but my knowleadge of Java is too little to get this done :(

**Comment by nickgieschen** [comment]
I'd be happy to resolve the conflicts, but don't want to put the effort in if it doesn't look like it's going to get merged. @vlasovskikh?

**Comment by vlasovskikh** [comment]
@nickgieschen Thanks again for your pull request and your changes after the review. It took me ages to get back to this one, terribly sorry about that. I've squashed your commits and rebased them onto master after fixing some inspection warnings and non-deterministic test results.

The fix is available in the EAP build 0.48.6. See https://github.com/JetBrains/ideavim#get-an-early-access for the instructions on how to get EAP builds as updates inside the IDE.

**Comment by pkrefta** [comment]
Thanks guys - just bought all products pack 👍

**Pull request closed without merging**
