### PR TITLE
Mapleader support based on the prototype of a Vim script expressions evaluator

### PR DESCRIPTION
**Pull request by vlasovskikh**
Currently only very simple `let` and `echo` commands are supported. Using the `mapleader` value in mappings is coming next.

### CODE REVIEW

**Comment by hari-rangarajan** [comment]
I haven't done any plugin development before. I'm wondering if it would be trivial to add a rudimentary ":command" method that would allow to alias ":action intellijinternalcommands" to be abbreviated to a shorter name? Thanks!

**Comment by tthanh** [comment]
I just update IdeaVim to version 4.1 and so happy with mapleader support. But went I use my old mapleader settings, I still can't use space like leader.
```
let mapleader = "\<Space>"
nnoremap <silent> <Leader>i :action ReformatCode<CR>
```

**Comment by vlasovskikh** [comment]
@tthanh Please file a bug about it [here](https://youtrack.jetbrains.com/issues/VIM).

**Comment by meonlol** [comment]
To use a space as a mapleader you can simply do:
```
let mapleader = " "
```

**Comment by cloudrave** [comment]
I can't seem to get the backslash `mapleader` to work.  I have the following currently:
```vim
let mapleader="\\"
```

**Comment by positron** [comment]
`let mapleader=" "` didn't work for me. I had to do `let mapleader=<Space>` for it to recognize space as my leader.

**Comment by a-b** [comment]
What is up to date way to use space key as a leader?
Tried both 

`let mapleader=<Space>`
`let mapleader=" "`

On lastest IDEA and IdeaVim, and seems like both are not working...

**Comment by plateauu** [comment]
Hi 
it is still `let mapleader = " "` 
You may try `noremap <SPACE> <Nop>` as well to disable any space actions

**Pull request merged**
