### PR TITLE
Fix VIM-1090 and VIM-1100 tag motion with duplicate tags.

### PR DESCRIPTION
**Pull request by Vvalter**
The current implementation of the tag motion does not handle multiple tags with the same name correctly. I was not able to adapt the current implementation. Instead I reimplemented the whole algorithm, trying to stay as close to the behavior of vim as possible. The runtime complexity is also improved as it should be at most linear in the size of the file instead of quadratic as before. (Try executing `dat` at the end of a file with 10000 `<a>` followed by 10000 `</a>` and IdeaVim will freeze with the current implementation.)

This pull request fixes [VIM-1090](https://youtrack.jetbrains.com/issue/VIM-1090) and [VIM-1100](https://youtrack.jetbrains.com/issue/VIM-1100). Possibly also [VIM-1155](https://youtrack.jetbrains.com/issue/VIM-1155), but the description of this issue is not clear enough to reproduce it.

### CODE REVIEW

**Comment by Vvalter** [comment]
Is there anything that I can do to get this merged soon?

**Comment by AlexPl292** [comment]
Hi!
Sorry for the long reply. PR review is paused because we are working on the VIM-510 issue. We will continue the review after completion of this task.

**Comment by AlexPl292** [comment]
Hi! 
I like your new approach, that gives better performance, but I was able to find a number of bugs.
Here are the cases where it doesn't work well:

```
<tr <caret>class="actions">
    <td width="100%" align="left">
        <a href="http://isitchristmas.com" class="button">Bing Bing bing</a>
    </td>
</tr>
```
```
            <tr <caret>class="actions">
                <td width="100%" align="left">
                    <a href="http://isitchri'stmas.com" class="button">Bing Bing bing</a>
                </td>
            </tr>
```
```
            <tr <caret>class="actions">
                <td width="100%" align="left">
                    <a href='http://isitchri"stmas.com' class="button">Bing Bing bing</a>
                </td>
            </tr>
```
```
            <<caret>div>
                <p>hey > hey < hey</p>
            </div>
```
```
<div <caret>hello="d > hsj < akl"></div>
```

**Comment by Vvalter** [comment]
Thank you for the review. The problem for the first three cases stem from incorrect handling of slashes in tags. I fixed this issue and added an appropriate test.

I couldn't really reproduce any issues with the last two cases. These seem to work fine for me, but I added one test case for them. Do you still have issues with those cases?

**Comment by Nimamoh** [comment]
successive |v_it| has a special behavior in vi, as well as when the caret not in a beginning of a line before a tag opening. it seems these case are not handled yet.

I used a bunch of tests in #189 that mostly cover successive selections, in case that would be useful :
`
 // |v_at|
  public void testNestedTagSelection() {

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      " <caret>  <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t>Inner</t> <caret> <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>  <t>Inner</t>\n" +
      "</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vatat"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("v2at"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</<caret>t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>");

    //
    configureByText("<<caret>t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>");

    //
    configureByText("<caret><t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vat"));
    assertSelection( "<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>");
  }

  // VIM-1633 |v_it|
  public void testNestedInTagSelection() {

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vit"));
    assertSelection("Inner");

    //
    configureByText("<t>Outer\n" +
      " <caret>  <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vit"));
    assertSelection( "Inner");

    //
    configureByText("<t>Outer\n" +
      " <caret>  <t></t>\n" +
      "</t>\n");
    typeText(parseKeys("vitit"));
    assertSelection("<t></t>");

    //
    configureByText("<t>Outer\n" +
      "   <t>Inner</t> <caret> <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vit"));
    assertSelection( "Outer\n" +
      "   <t>Inner</t>  <t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("v2it"));
    assertSelection("Outer\n" +
      "   <t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vitit"));
    assertSelection("<t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t><caret>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vititit"));
    assertSelection("Outer\n" +
      "   <t>Inner</t>");

    //
    configureByText("<t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</<caret>t>\n");
    typeText(parseKeys("vit"));
    assertSelection( "Outer\n" +
      "   <t>Inner</t>");

    //
    configureByText("<<caret>t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vit"));
    assertSelection( "Outer\n" +
      "   <t>Inner</t>");

    //
    configureByText("<caret><t>Outer\n" +
      "   <t>Inner</t>\n" +
      "</t>\n");
    typeText(parseKeys("vit"));
    assertSelection( "Outer\n" +
      "   <t>Inner</t>");

  }
`

**Comment by Vvalter** [comment]
Thanks for the test cases. These features should be pretty straightforward to implement. However, I would like to know if this pull request has a chance of being merged before spending more time with it.

@AlexPl292 do you prefer this approach or the one of #189? I see advantages of both approaches: This approach should have better performance and less code size and complexity (depending on how familiar the reader is with regular expressions), but the other approach can be seen as more explicit and cleaner, because there are no cryptic regexes. 
I think in the end it is a matter of taste which approach is better.

Currently #189 handles some edge cases and successive selection better, but I would be willing to implement these in this pull request as long as I know it will be merged eventually and my work is not wasted...

**Comment by AlexPl292** [comment]
Yeah, we ended up deciding on a solution from @Vvalter.

@Nimamoh thank you for your work. Bracket fixes are going to master, of course. Could you please roll back the changes that are related to the tags?

@Vvalter, do I understand correctly that there are still moments left that you would like to finish?
It would be great if you could use the tests that @Nimamoh wrote. They look pretty detailed.

**Comment by Vvalter** [comment]
> @Vvalter, do I understand correctly that there are still moments left that you would like to finish?
> It would be great if you could use the tests that @Nimamoh wrote. They look pretty detailed.

Yes I will incorporate the tests of @Nimamoh (thanks for them!) and implement successive selection. I am pretty busy right now, so this will take me a couple of days, but it should be done by Sunday.

**Comment by Vvalter** [comment]
I implemented the successive tag block selection and fixed some minor issues. This should emulate vim behavior pretty closely, but I am sure there are some discrepancies left, because there are some many special cases...
I was able to copy lot of testcases and some other code from @Nimamoh pull request. Thanks!

**Comment by AlexPl292** [comment]
Great news! I've checked the PR and I think it could be merged.

Thank you for your contribution!

**Pull request merged**
