### PR TITLE
Vim-830 - Implement the :normal command

### PR DESCRIPTION
**Pull request by AlexPl292**
Implementation for `:normal` command.
https://youtrack.jetbrains.com/issue/VIM-830

---
Currently, the `<Esc>`, `<C-A>`, etc. commands could be entered as they are (e.g. `:norm iHelloWorld<Esc>`). Entering such commands in the vim-way will be possible after the implementation of  `i_CTRL-V` command.

### CODE REVIEW

**Comment by MicGon7** [comment]
I am looking forward to having this command added to ideaVim. It would be a huge efficiency boost to my workflow in ideaVim and would allow me to continue using it for production Android app development.

**Comment by nearmax** [comment]
Is this PR abandoned?

**Comment by AlexPl292** [comment]
@nearmax Hi! No, this PR is not abandoned, but we've encountered some technical problems that need to be solved before this PR can be merged. In other cases it will be useless.

**Comment by augustobmoura** [comment]
We can help with the problems or are they internal in Intellij Pro?

**Comment by afonsomatos** [comment]
This would be very helpful. I'm wanting to run a macro in selected lines with `:'<,'>normal @a`, but it's not working.

**Comment by FullstackGJJ** [comment]
I too am curious to know if we can help with any technical problems. This feature is what I miss the most from normal vim while I'm working in IntelliJ.

**Comment by shane-lamb** [comment]
@AlexPl292 can you go into detail on the problems? Would love to see this feature released. Thanks.

**Comment by softarn** [comment]
I'm in need of this. Please tell me if you need help fixing this.

**Comment by knarka** [comment]
Any progress on this? Can I help in any way to get this merged? Really missing this feature in ideavim.

**Comment by AlexPl292** [comment]
Normal command will be available with the next release 1.9.0

**Comment by SamuelTissot** [comment]
omg thank you so much.

**Pull request closed without merging**
