### PR TITLE
Add tag action (VIM-364)

### PR DESCRIPTION
**Pull request by lubba**
http://youtrack.jetbrains.com/issue/VIM-264

### CODE REVIEW

**Comment by doMynation** [comment]
:+1:

**Comment by lubba** [comment]
@1984weed thank you for your request! I made some changes in it and added tests. I hope, you will comment and review my code too.

**Comment by 1984weed** [comment]
I reviewed your test and refactoring code. My code was useless a part and lack of test codes. Thanks your pull request.

I think we should add test that tag has attribute. like following this. :smile: 
```java
 public void  testDeleteInnerTagBlockInOpenOnAttrib(){
    typeTextInFile(parseKeys("dit"),"abcde<tag class='nam<caret>e'>fg</tag>hi");
    myFixture.checkResult("abcde<tag class='name'></tag>hi");
  }
```

**Comment by lubba** [comment]
@doMynation, I think, it will be soon

**Comment by lubba** [comment]
@1984weed, thanks for your words.
I added tests for tags with argument as you said. And now at refactoring they were really useful!

**Comment by vlasovskikh** [comment]
@lubba @1984weed Thanks for your contributions! I've rebased your work on top of the master branch.

**Comment by doMynation** [comment]
Oh god I'm so excited. 

Big thanks to you guys!

**Comment by abrahamD** [comment]
When is the next release? :D :D :D

**Comment by doMynation** [comment]
I can't wait !! :)

**Comment by Baldrs** [comment]
@vlasovskikh @lubba 

given such html, with cursor being at `>>>cursor<<<`:

```html
            <div class="container">
>>>selection correct start<<<
                <p>{% trans %}sometext{% endtrans %}</p>
                <p>{% trans %}sometext{% endtrans %}</p>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" class="formCheckbox" id="someid"
                               value="accept"> {% trans from "messages-v2" %}i18n.page.confirmation.request{% endtrans %}
                        <div id="info_error"
                             class="error">>>>selection actual start<<<{% trans %}some text{% endtrans %}</div>
                    </label>
                </div>
                 >>>cursor and selection end<<<
                <hr class="bemElementWasHere-hr">
            </div>
```

When I press <kbd>vit</kbd>, instead of selecting inner contents of `containter`, selection start ends at `error` which is closest div element.

**Comment by Baldrs** [comment]
In general it happens for big enough blocks of code, when opening tag type appears earlier than actual opening tag

**Comment by vlasovskikh** [comment]
@Baldrs Please file a bug to https://youtrack.jetbrains.com/issues/VIM.

**Comment by Baldrs** [comment]
https://youtrack.jetbrains.com/issue/VIM-1100

**Pull request closed without merging**
