### PR TITLE
Add feature tag action in text object.

### PR DESCRIPTION
**Pull request by 1984weed**
Hello

I'm one of user who love this project. 
I added feature for html tag object of vim.

I hope you to check my code and merge.

Thank you

### CODE REVIEW

**Comment by Baldrs** [comment]
Given such snippet(oppened with patched ideavim and vim):
```html
<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>
```

When caret on `</button>`, vit selects `Click Me`, that's ok.
When caret on `<button>` vit selects `<template>` inner content -> must select `Click Me`
When caret on `name` attribute, vit does nothing. In vim: selects inner of `template`
When caret is on `<template` and it is a top-level tag, throws `java.lang.ArrayIndexOutOfBoundsException`

`at` variant is affected by the same issues

**Comment by 1984weed** [comment]
Thanks for Baldrs
I fixed these bug.
* when caret in html tag select, adjust select range
* when caret on top-level tag, java.lang.ArrayIndexOutOfBoundsException doesn't cause

**Comment by Baldrs** [comment]
Given such html:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head> 

<body>

</body>
<foo>
  <bar></bar>
</foo>
</html>
```
When cursor is after `</head>` and before `<body>` `vit` does not work(nothing happens). In vim: selects anything between `<html>` and `</html>`
When cursor is on `</html>` or `</head>` `vit` does nothing, however on </foo> and </body>(same level of nesting) it does select them as intended.
When tag is empty, it selects `><` between opening and closing tag. In vim: cursor moves to be before `<` of closing tag, no selection is made.

When on `>` of tag, `vat` selects only this character, in vim it selects tag as it should(i.e. full tag). `vit` does the same thing.

When on self-closing tags, it selects character under cursor for both `vat` and `vit`, however in vim it ignores and selects parent.

**Comment by porn** [comment]
:thumbsup: on this issue! I'm so missing this feature in IdeaVIM.

Thank you guys in advance for both: the implementation and the throughout testing!

**Comment by 1984weed** [comment]
thanks

I fixed following bugs
* when include unclose tag, select behavior
* when on ```>``` caret, select behavior

I didn't fix bugs when empty tag, because I can't adjust start position and end position in this ideavim structure.

**Comment by porn** [comment]
@Baldrs: is there any chance to merge this pull request while creating new issues for ...the new issues? :wink:

**Comment by vlasovskikh** [comment]
@1984weed Thank you for your pull request. It's not the first one trying to implement vit/vat commands. It turns out that there are lots of cases that need to be covered by an implementation. I will check your PR against several tests known to be (there are no unit tests for that at the moment) and if it fails I'll attach the corresponding unit tests.

**Comment by Baldrs** [comment]
@porn I just testing this PR because I need such functionality in  PhpStorm, but I don't merge anything :smile:

**Comment by vlasovskikh** [comment]
@Baldrs Thanks for testing it. I appreciate your effort. Please keep reporting any problems with it here.

**Comment by atwoz** [comment]
Let's get this merged, it would be great to have the tag feature.

**Comment by ryross** [comment]
+1. This would be really nice! Nice work @1984weed @vlasovskikh did this fail any of the unit tests?

**Comment by vlasovskikh** [comment]
I've merged #100 instead of this one. It is based on the commits of @1984weed and @lubba. You can try builds >= 298 from the [CI server](https://teamcity.jetbrains.com/project.html?projectId=IdeaVim&guest=1).

**Pull request closed without merging**
