### PR TITLE
={motion} implementation, == with count and fix for VIM-259

### PR DESCRIPTION
**Pull request by ayzenquwe**
This PR fixes VIM-259, allows using counts for == and adds ={motion} action.

### CODE REVIEW

**Comment by porn** [comment]
Please, please, someone merge this one I'm desperately needing `=ap`

**Comment by porn** [comment]
any chance this will get merged?

**Comment by dhleong** [comment]
:+1: 

@vlasovskikh Any issues with this PR?

**Comment by ayzenquwe** [comment]
By the way, it appears that this also fixes VIM-217 and VIM-246 :)

**Comment by vlasovskikh** [comment]
@ayzenquwe Thank you for your pull requests! Sorry it took me so long to finally review and merge them. The quality of the PRs was really good, I haven't found any problems with them.

**Comment by ayzenquwe** [comment]
@vlasovskikh  Thanks! Glad you found the time to do that. :)

**Pull request merged**
